local fn = vim.fn
local o = vim.opt
local g = vim.g

g.mapleader = ","
o.backup = false -- creates a backup file
o.breakindent = true
o.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
o.cmdheight = 1 -- space for displaying messages/commands
o.completeopt = { "menu", "menuone", "noselect", "noinsert" } -- A comma separated list of options for Insert mode completion
o.conceallevel = 0 -- so that `` is visible in markdown files
o.cursorline = true -- highlight the current line
o.dir = fn.stdpath("data") .. "/swp" -- swap file directory
o.expandtab = true -- convert tabs to spaces
o.fileencoding = "utf-8" -- the encoding written to a file
o.foldcolumn = "1"
o.foldenable = false -- don't start files folded; enable with zi; wait for https://github.com/neovim/neovim/pull/17446
o.foldlevelstart = 99 -- Using ufo provider need a large value, feel free to decrease the value
o.history = 500 -- Use the 'history' option to set the number of lines from command mode that are remembered.
o.hlsearch = true -- highlight all matches on previous search pattern
o.ignorecase = true -- ignore case in search patterns
o.laststatus = 3 -- global statusline = 3
o.lazyredraw = true -- do not redraw screen while running macros
o.list = true
o.mouse = ""
o.number = true -- standard line numbers are fine
o.scrolloff = 3 -- Minimal number of screen lines to keep above and below the cursor
o.shiftwidth = 2 -- the number of spaces inserted for each indentation
o.shortmess = o.shortmess + "c" -- prevent "pattern not found" messages
o.showmode = false -- we don't need to see things like -- INSERT -- anymore
o.sidescrolloff = 5 -- the minimal number of columns to scroll horizontally
o.signcolumn = "yes" -- "yes" ensures that the gutter doesn't open and close spastically
o.smartcase = true -- smart case
o.smartindent = true -- make indenting smarter again
o.splitbelow = true -- force all horizontal splits to go below current window
o.splitright = true -- force all vertical splits to go to the right of current window
o.swapfile = true -- enable/disable swap file creation
o.tabstop = 2 -- how many columns a tab counts for
o.termguicolors = true -- set term gui colors (most terminals support this)
o.timeoutlen = 400 -- time to wait for a mapped sequence to complete (in milliseconds)
o.ttimeoutlen = 0 -- time in milliseconds to wait for a key code sequence to complete
o.undodir = fn.stdpath("data") .. "/undodir" -- set undo directory
o.undofile = true -- enable/disable undo file creation
o.updatetime = 250 -- faster completion
o.wildignorecase = true -- When set case is ignored when completing file names and directories
o.wildmode = "full"
o.wrap = false
